flowchart TB
    SCADA["SCADA-Server<br/>192.168.10.200"]
    SW["Industrial Switch"]
    CNC1["CNC-01<br/>Modbus TCP<br/>192.168.10.100"]
    CNC2["CNC-02<br/>Modbus TCP<br/>192.168.10.101"]
    ROB["Robot-01<br/>MQTT / OPC UA<br/>192.168.10.102"]
    PRESS["Press-01<br/>Modbus TCP<br/>192.168.10.103"]
    SENS["Sensor-01<br/>MQTT<br/>192.168.10.104"]
    SCADA --- SW
    SW --- CNC1
    SW --- CNC2
    SW --- ROB
    SW --- PRESS
    SW --- SENS
